defmodule MossletWeb.Endpoint do
  use Sentry.PlugCapture
  use Phoenix.Endpoint, otp_app: :mosslet

  # Enable concurrent testing for Wallaby
  if sandbox = Application.compile_env(:mosslet, :sandbox, false) do
    plug Phoenix.Ecto.SQL.Sandbox, sandbox: sandbox
  end

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_mosslet_key",
    signing_salt: {Mosslet.Encrypted.Session, :signing_salt, []},
    encryption_salt: {Mosslet.Encrypted.Session, :encryption_salt, []},
    same_site: "Lax"
  ]

  # We pass the `:user_agent` in the websocket for Wallaby testing
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:user_agent, session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # redirect requests through the canonical host
  plug(:canonical_host)

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :mosslet,
    gzip: not code_reloading?,
    only: MossletWeb.static_paths()

  # Tidewave ai support
  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :mosslet
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Stripe.WebhookPlug,
    at: "/webhooks/stripe",
    handler: Mosslet.Billing.Providers.Stripe.WebhookHandler,
    secret: {Application, :get_env, [:stripity_stripe, :signing_secret]}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # 8 MB by trix.js calculations
    length: 8_388_608

  plug Sentry.PlugContext

  plug MossletWeb.Plugs.ContentSecurityPolicy

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  plug RemoteIp,
    headers: ~w[http_fly_client_ip]

  plug MossletWeb.Plugs.BotDefense

  plug MossletWeb.Router

  defp canonical_host(conn, _opts) do
    :mosslet
    |> Application.get_env(:canonical_host)
    |> case do
      host when is_binary(host) ->
        opts = PlugCanonicalHost.init(canonical_host: host)
        PlugCanonicalHost.call(conn, opts)

      _ ->
        conn
    end
  end
end
